In [3]:
# 01_data_cleaning.ipynb
import pandas as pd
import numpy as np
import os

df_raw = pd.read_excel("../data/TMT_data.xlsx", parse_dates=["Invoice_Date"])

cols_to_keep = [
    "Invoice_Date",
    "Material_Name",
    "Quantity_MT",
    "Total_Invoice_Value",
    "Unit_Price",
    "UOM",
    "Vendor_Name"
]
df = df_raw[cols_to_keep].copy()

df = df[df["Quantity_MT"] >= 0]
df["Quantity_MT"] = pd.to_numeric(df["Quantity_MT"], errors="coerce")
df["Unit_Price"] = pd.to_numeric(df["Unit_Price"], errors="coerce")

df = df.dropna(subset=["Invoice_Date", "Unit_Price"])
df = df.sort_values("Invoice_Date")

os.makedirs("../data", exist_ok=True)
df.to_csv("../data/cleaned_tmt_data.csv", index=False)

print("✅ Cleaning complete. Saved to ../data/cleaned_tmt_data.csv")
df.head()

✅ Cleaning complete. Saved to ../data/cleaned_tmt_data.csv

,Invoice_Date,Material_Name,Quantity_MT,Total_Invoice_Value,Unit_Price,UOM,Vendor_Name
785,2022-05-19,TMT REBAR FE500D DIA 12MM,8.98,659625.9,61750.0,MTS,MS AGARWAL FOUNDRIES PRIVATE LIMITED
784,2022-05-19,TMT REBAR FE500D DIA 20MM,19.94,1464692.7,61750.0,MTS,MS AGARWAL FOUNDRIES PRIVATE LIMITED
782,2022-05-21,TMT REBAR FE500D DIA 10MM,7.98,567338.1,60250.0,MTS,Rawmart Material Solutions Pvt Ltd
780,2022-05-21,TMT REBAR FE500D DIA 16MM,11.60,824702.0,60250.0,MTS,Rawmart Material Solutions Pvt Ltd
783,2022-05-21,TMT REBAR FE500D DIA 8MM,9.58,692394.5,61250.0,MTS,Rawmart Material Solutions Pvt Ltd